create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  client_order_id text not null unique,
  created_at timestamptz not null default now(),
  status text not null default 'new'
    check (status in ('new', 'accepted', 'preparing', 'ready', 'completed', 'cancelled')),
  source text not null default 'telegram_web_app',
  telegram_user_id text,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  customer_name text,
  phone text,
  fulfillment_method text not null
    check (fulfillment_method in ('pickup', 'dine_in', 'delivery')),
  address text,
  note text,
  currency text not null default 'USD'
    check (currency in ('USD', 'KHR')),
  subtotal_usd numeric(10, 2) not null check (subtotal_usd >= 0),
  subtotal_khr integer not null check (subtotal_khr >= 0),
  item_count integer not null check (item_count > 0 and item_count <= 99),
  items jsonb not null check (jsonb_typeof(items) = 'array'),
  telegram_user jsonb,
  raw_client jsonb not null default '{}'::jsonb
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status, created_at desc);

alter table public.orders enable row level security;

revoke all on table public.orders from anon, authenticated;
grant select, insert, update on table public.orders to anon, authenticated;
grant select, insert, update, delete on table public.orders to service_role;
grant usage, select on sequence public.orders_id_seq to anon, authenticated, service_role;

drop policy if exists "Anyone can view orders" on public.orders;
create policy "Anyone can view orders"
on public.orders
for select
to anon, authenticated
using (true);

drop policy if exists "Guests can place orders" on public.orders;
create policy "Guests can place orders"
on public.orders
for insert
to anon, authenticated
with check (
  status = 'new'
  and source = 'telegram_web_app'
  and item_count > 0
  and item_count <= 99
  and jsonb_typeof(items) = 'array'
  and jsonb_array_length(items) > 0
  and subtotal_usd >= 0
  and subtotal_khr >= 0
);

drop policy if exists "Guests can update order status" on public.orders;
create policy "Guests can update order status"
on public.orders
for update
to anon, authenticated
using (true)
with check (
  status in ('new', 'accepted', 'preparing', 'ready', 'completed', 'cancelled')
);
